---
- name: "create admin group (is written in sudoers file from the first)"
  group:
    name: admin
    gid: 5001

- name: "create common group"
  group:
    name: common
    gid: 5002

- name: "create docker group"
  group:
    name: docker
    gid: 5003

- name: "allow sudo make to common"
  lineinfile:
    dest: /etc/sudoers
    line: "%common ALL=(root) /usr/bin/make"

- name: "allow sudo docker to common"
  lineinfile:
    dest: /etc/sudoers
    line: "%common ALL=(root) /usr/bin/docker"
