---
- name: "create admin user: {{ username }}"
  user:
    name: "{{ username }}"
    uid: "{{ uid }}"
    group: admin
    groups: docker
    create_home: yes
    home: "/home/{{ username }}"
    password: "{{ password }}"
    update_password: on_create
    shell: /bin/bash

### SSH config
- include_tasks: M001_ssh_config.yml
  vars:
    home: "/home/{{ username }}"
